"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.CommandsData = void 0;
var CommandsData;
(function (CommandsData) {
    CommandsData["RelativeMove"] = "RelativeMove";
    CommandsData["KP"] = "KP";
    CommandsData["KI"] = "KI";
    CommandsData["KD"] = "KD";
    CommandsData["IntegrationLimit"] = "IL";
    CommandsData["VelocityFeedForward"] = "VFF";
    CommandsData["AccelerationFeedForward"] = "AFF";
    CommandsData["BIAS"] = "BIAS";
    CommandsData["MotorOutputLimit"] = "MLIMIT";
    CommandsData["DerivativeSampleInterval"] = "DS";
    CommandsData["MaxError"] = "Max";
    CommandsData["AutoStopMode"] = "AStop";
    CommandsData["ECPR"] = "ECPR";
    CommandsData["Velocity"] = "Vel";
    CommandsData["Acceleration"] = "Acc";
    CommandsData["Decceleration"] = "Dec";
    CommandsData["AbsMove"] = "Abs";
    CommandsData["Position"] = "Pos";
    CommandsData["PWM"] = "Pwm";
})(CommandsData || (CommandsData = {}));
exports.CommandsData = CommandsData;
