"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.Commands = void 0;
var Commands;
(function (Commands) {
    Commands["FW_VER"] = "FW_VER";
    Commands["ENCODER"] = "ENCODER";
    Commands["FOLLOWING_ERROR"] = "FOLLOWING_ERROR";
    Commands["POWER_ON"] = "POWER_ON";
    Commands["POWER_OFF"] = "POWER_OFF";
    Commands["SERVO_ON"] = "SERVO_ON";
    Commands["SERVO_OFF"] = "SERVO_OFF";
    Commands["STATUS"] = "STATUS";
    Commands["INPUTS"] = "INPUTS";
    Commands["STOP"] = "STOP";
    Commands["AXIS1"] = "AXIS1";
    Commands["AXIS2"] = "AXIS2";
    Commands["GO"] = "GO";
    Commands["AXES"] = "AXES";
    Commands["STOP_TRACE"] = "trace 0";
})(Commands || (Commands = {}));
exports.Commands = Commands;
